export interface WownetWordModel {
	comId : String;
	ctrName : String;
	ctrCd : String;
	mBuyer : String;
	mCenter : String;
	mConsumer : String;
	mCountry : String;
	mDownline : String;
	mEducation : String;
	mFirstName : String;
	mGetBank : String;
	mGetTax : String;
	mGroup : String;
	mJuminNo : String;
	mLastName : String;
	mMember : String;
	mModiileName : String;
	mParents : String;
	mRank : String;
	mRecomm : String;
	mUserKind : String;
	oAccDate : String;
	oAutoship : String;
	oBarcode : String;
	oOrdKind : String;
	oOrdPath : String;
	oOrder : String;
	oProduct : String;
	oPv1 : String;
	oPv2 : String;
	oPv3 : String;
	oSerialNo : String;
	oStore : String;
	pPay : String;
	oMileage: String;
}