export interface KICCCardModel {
  resCd: String;
	resMsg: String;
	pgCno: String;
	amount: Number;
	shopTransactionId: String;
	shopOrderNo: String;
	approvalNo: String;
	transactionDate: String;
	escrowUsed: String;
	complexUsed: String;
	statusCode: String;
	statusMessage: String;
	payMethodTypeCode: String;
	customerName: String;
	mallId: String;
	cardNo: String;
	issuerCode: String;
	issuerName: String;
	acquirerCode: String;
	acquirerName: String;
	installmentMonth: String;
	freeInstallmentTypeCode: String;
	joinNo: String;
	partCancelUsed: String;
	cardGubun: String;
	cardBizGubun: String;
	couponFlag: String;
	couponAmount: String;
	cancelAcqDate: String;
	bankCode: String;
	bankName: String;
	accountNo: String;
	depositName: String;
	expiryDate: String;
	basketUsed: String;
	cashResCd: String;
	cashResMsg: String;
	cashAuthNo: String;
	cashTranDate: String;
	cancelDate: String;
	refundDate: String;
	pointUsed: String;
	unimileUsed: String;
	dayRemPnt: String;
	monthRemPnt: String;
	dayRemCnt: String;
	oilListCnt: String;
	oilInfo: String;
	orderNo: String
	trdNo :String
	authDate : String
}