export interface PayPrintModel {
	 accholder : String;
	 accnumber : String;
	 paymentdate : String;
	 paymentDate: String;
	 memberName: String;
	 cmnd: String;
	 totalBeforeTax: String;
	 vat: String;
	 actualPayment: String;
	 amtCarriedForward: String;
	 bank: String;
	 accNumber: String;
	 accHolder: String;
	 date: String;
	 ynname: String;
	 kindName: String;
	 username: String;
	 userNameEng: String;
	 birthday: String;
	 country: String;
	 center: String;
	 grp: String;
	 pname: String;
	 rname: String;
	 mobile: String;
	 email: String;
	 accno: String;
	 depositor: String;
	 post: String;
	 addr1: String;
	 addr2: String;
	 paycd: String;
	 payname: String;
	 tglv: String;
	 tgamt: String;
	 basic: String;
	 ordno: String;
	 rate: String;
     remark: String;
	
	 regdate: String;
	 fixYNName: String;
	 giveDate: String;
	 giveDate1: String;
	 giveKindName: String;
	 userid: String;
	 ctrName: String;
	 rankName: String;
	 cntName: String;
	 grpName: String;
	 juminNO: String;
	 juminDate: String;	
	 bankName: String;
	 accNo: String;
	 taxKindName: String;
	 totalBe: String;
	 amt1: String;
	 amt2: String;
	 amt3: String;
	 amt4: String;
	 amt5: String;
	 amt6: String;
	 amt7: String;
	 amt8: String;
	 amt9: String;
	 amt10: String;
	 amt11: String;
	 amt12: String;
	 amt13: String;
	 amt14: String;
	 amt15: String;
	 amtEtcB: String;
	 amtLoanB: String;
	 amtRDB: String;
	 totalAmt: String;
	 totalRe: String;
	 tax1Amt: String;
	 tax2Amt: String;
	 tax3Amt: String;
	 bankAmt: String;
	 amtEtcA: String;
	 amtLoanA: String;
	 antRDA: String;
	 trueAmt: String;
	 sum: String;
	
	 address: String;
	 taxIncome: String;
	 taxResident: String;
	 gubun: String;
	
	 userName: String;
	 juminNoOrg: String;
	 taxAddress: String;
	
	 year: String;
	 month: String;
	 day: String;
	 taxTotalAmt: String;


}