export interface ConsumerSalesRegistrationModel{
regDate : string ;
birthDay : string ;
mobile : string ;
email : string ;
post : string ;
rid : string ;
consumerId : string ;
consumerName : string ;
addr1 : string ;
addr2 : string ;
remark : string ;
workDate : string ;
workUser : string ;
rankRId : string ;
rName : string ;
userId : string ;
userName : string ;
ordNo : string ;
ordDate : string ;
pdtCd : string ;
pdtName : string ;
unsoldQty : string ;
unsoldAmt : string ;
saleQty : string ;
saleAmt : string ;
ordAmt : string ;
salePrice : string ;
salePriceRate : string ;
unsoldAmtRate : string ;
year : string ;
month : string ;
pdtQty : string ;
pdtPrice : string ;
pankName : string ;
cntName : string ;
pdtSeq : string ;

}