export interface AnalysisMember {
    cntAct      : string
    cntTerm     : string
    cnt         : string
    rateTerm    : string
    ordAmt      : string
    ordAmtBf    : string
    ordAmtTotal : string
    ordUserCnt  : string
    eachCost    : string
    ordCnt      : string
    ordCntA     : string
    ordRate     : string
    payOrdAmt   : string
    payTotalAmt : string
    payRate     : string
    rankCD      : string
    rankName    : string
    cntAge10    : string
    cntAge20    : string
    cntAge30    : string
    cntAge40    : string
    cntAge50    : string
    cntAge60    : string
    cntAge70    : string
    cntAgeOther : string
    cntMem      : string
    cntCD       : string
    cntName     : string
    rate        : string
    grpCD       : string
    grpName     : string
}